# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: sonic-erc20indexer
description: Sonic ERC-20 indexer
networks:
  - id: 146 # Sonic Mainnet
    start_block: 10861674
    contracts:
      - name: ERC20
        # address: "0x0000000000000000000000000000000000000000" # any token
        handler: src/EventHandlers.ts
        events:
          - event: "Approval(address indexed owner, address indexed spender, uint256 value)"
          - event: "Transfer(address indexed from, address indexed to, uint256 value)"
# Unordered multichain mode allows you to index events from multiple chains
# in realtime but doesn't guarentee ordering between chains
# https://docs.envio.dev/docs/HyperIndex/multichain-indexing#unordered-multichain-mode
unordered_multichain_mode: true
